//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StreamingApp.StreamingServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="StreamingServiceReference.IStreamingService")]
    public interface IStreamingService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStreamingService/GetChannelList", ReplyAction="http://tempuri.org/IStreamingService/GetChannelListResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Termors.Services.Tv.MPStreamingInterface.StreamingFault), Action="http://tempuri.org/IStreamingService/GetChannelListStreamingFaultFault", Name="StreamingFault", Namespace="http://schemas.datacontract.org/2004/07/Termors.Services.Tv.MPStreamingInterface")]
        Termors.Services.Tv.MPStreamingInterface.ChannelList GetChannelList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStreamingService/StartStreaming", ReplyAction="http://tempuri.org/IStreamingService/StartStreamingResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Termors.Services.Tv.MPStreamingInterface.StreamingFault), Action="http://tempuri.org/IStreamingService/StartStreamingStreamingFaultFault", Name="StreamingFault", Namespace="http://schemas.datacontract.org/2004/07/Termors.Services.Tv.MPStreamingInterface")]
        Termors.Services.Tv.MPStreamingInterface.StreamingResult StartStreaming(int channelId, bool record, bool copyToFtp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStreamingService/StopStreaming", ReplyAction="http://tempuri.org/IStreamingService/StopStreamingResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Termors.Services.Tv.MPStreamingInterface.StreamingFault), Action="http://tempuri.org/IStreamingService/StopStreamingStreamingFaultFault", Name="StreamingFault", Namespace="http://schemas.datacontract.org/2004/07/Termors.Services.Tv.MPStreamingInterface")]
        void StopStreaming(Termors.Services.Tv.MPStreamingInterface.StreamingResult stresult);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStreamingService/GetStreamingStatus", ReplyAction="http://tempuri.org/IStreamingService/GetStreamingStatusResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Termors.Services.Tv.MPStreamingInterface.StreamingFault), Action="http://tempuri.org/IStreamingService/GetStreamingStatusStreamingFaultFault", Name="StreamingFault", Namespace="http://schemas.datacontract.org/2004/07/Termors.Services.Tv.MPStreamingInterface")]
        Termors.Services.Tv.MPStreamingInterface.StreamingResult[] GetStreamingStatus();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStreamingService/GetConfiguration", ReplyAction="http://tempuri.org/IStreamingService/GetConfigurationResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Termors.Services.Tv.MPStreamingInterface.StreamingFault), Action="http://tempuri.org/IStreamingService/GetConfigurationStreamingFaultFault", Name="StreamingFault", Namespace="http://schemas.datacontract.org/2004/07/Termors.Services.Tv.MPStreamingInterface")]
        Termors.Services.Tv.MPStreamingInterface.StreamingSettings GetConfiguration();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStreamingService/SetConfiguration", ReplyAction="http://tempuri.org/IStreamingService/SetConfigurationResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Termors.Services.Tv.MPStreamingInterface.StreamingFault), Action="http://tempuri.org/IStreamingService/SetConfigurationStreamingFaultFault", Name="StreamingFault", Namespace="http://schemas.datacontract.org/2004/07/Termors.Services.Tv.MPStreamingInterface")]
        void SetConfiguration(Termors.Services.Tv.MPStreamingInterface.StreamingSettings settings);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IStreamingServiceChannel : StreamingApp.StreamingServiceReference.IStreamingService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StreamingServiceClient : System.ServiceModel.ClientBase<StreamingApp.StreamingServiceReference.IStreamingService>, StreamingApp.StreamingServiceReference.IStreamingService {
        
        public StreamingServiceClient() {
        }
        
        public StreamingServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StreamingServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StreamingServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StreamingServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Termors.Services.Tv.MPStreamingInterface.ChannelList GetChannelList() {
            return base.Channel.GetChannelList();
        }
        
        public Termors.Services.Tv.MPStreamingInterface.StreamingResult StartStreaming(int channelId, bool record, bool copyToFtp) {
            return base.Channel.StartStreaming(channelId, record, copyToFtp);
        }
        
        public void StopStreaming(Termors.Services.Tv.MPStreamingInterface.StreamingResult stresult) {
            base.Channel.StopStreaming(stresult);
        }
        
        public Termors.Services.Tv.MPStreamingInterface.StreamingResult[] GetStreamingStatus() {
            return base.Channel.GetStreamingStatus();
        }
        
        public Termors.Services.Tv.MPStreamingInterface.StreamingSettings GetConfiguration() {
            return base.Channel.GetConfiguration();
        }
        
        public void SetConfiguration(Termors.Services.Tv.MPStreamingInterface.StreamingSettings settings) {
            base.Channel.SetConfiguration(settings);
        }
    }
}
