//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Termors.Services.Tv.MPStreamingService {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("giulia3.termors.net")]
        public string TvServerHost {
            get {
                return ((string)(this["TvServerHost"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("52000")]
        public int DebugInterruptTcpPort {
            get {
                return ((int)(this["DebugInterruptTcpPort"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TwitterEnabled {
            get {
                return ((bool)(this["TwitterEnabled"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("W:\\Streaming")]
        public string OutputDirectory {
            get {
                return ((string)(this["OutputDirectory"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("stream")]
        public string BaseFileName {
            get {
                return ((string)(this["BaseFileName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"-i {0} -map 0:{2} -filter:v yadif -vcodec libx264 -preset veryfast -profile:v baseline -level 30 -maxrate {9}k -bufsize 10000000 -b:v {4}k -s {6} -threads 0 -f segment -segment_list {1}.m3u8 -segment_list_flags +live -segment_time {7} -segment_wrap {8} -bsf h264_mp4toannexb -flags -global_header -map 0:{3} -acodec aac -ac 2 -strict experimental -b:a {5}k {1}%03d.ts")]
        public string FFMpegCommandLine {
            get {
                return ((string)(this["FFMpegCommandLine"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\Temp\\ffmpeg\\bin\\ffmpeg.exe")]
        public string FFMpegPath {
            get {
                return ((string)(this["FFMpegPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.termors.net/streaming/stream.m3u8")]
        public string LocalStreamingUrl {
            get {
                return ((string)(this["LocalStreamingUrl"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\Temp\\ffmpeg\\bin\\ffprobe.exe")]
        public string FFProbePath {
            get {
                return ((string)(this["FFProbePath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-i {0} -show_streams -v quiet -print_format xml")]
        public string FFProbeCommandLine {
            get {
                return ((string)(this["FFProbeCommandLine"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("termorslive.net16.net")]
        public string FtpHost {
            get {
                return ((string)(this["FtpHost"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("a5847925")]
        public string FtpUser {
            get {
                return ((string)(this["FtpUser"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("yoghurt19")]
        public string FtpPassword {
            get {
                return ((string)(this["FtpPassword"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/public_html/database")]
        public string FtpRemoteDir {
            get {
                return ((string)(this["FtpRemoteDir"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.termorslive.net16.net/database/stream.m3u8")]
        public string RemoteStreamingUrl {
            get {
                return ((string)(this["RemoteStreamingUrl"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public ushort FtpConcurrentJobs {
            get {
                return ((ushort)(this["FtpConcurrentJobs"]));
            }
            set {
                this["FtpConcurrentJobs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("400")]
        public ushort VideoBitrateKbps {
            get {
                return ((ushort)(this["VideoBitrateKbps"]));
            }
            set {
                this["VideoBitrateKbps"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("48")]
        public ushort AudioBitrateKbps {
            get {
                return ((ushort)(this["AudioBitrateKbps"]));
            }
            set {
                this["AudioBitrateKbps"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("360x288")]
        public string VideoSize {
            get {
                return ((string)(this["VideoSize"]));
            }
            set {
                this["VideoSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public ushort SegmentFileLengthSec {
            get {
                return ((ushort)(this["SegmentFileLengthSec"]));
            }
            set {
                this["SegmentFileLengthSec"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public ushort SegmentCount {
            get {
                return ((ushort)(this["SegmentCount"]));
            }
            set {
                this["SegmentCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("600")]
        public ushort VideoMaxBitrateKbps {
            get {
                return ((ushort)(this["VideoMaxBitrateKbps"]));
            }
            set {
                this["VideoMaxBitrateKbps"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("dlImhT0hAeM1BAxrqUg6w")]
        public string TwitterConsumerKey {
            get {
                return ((string)(this["TwitterConsumerKey"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("nmlWqhppzhwUjATiD8b3OnRiBIwZqZNF8yGCJhGRj9s")]
        public string TwitterConsumerSecret {
            get {
                return ((string)(this["TwitterConsumerSecret"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1352280254-bbffWme573aj8pkWgukoIEwuY088GTvTCNbi6Ec")]
        public string TwitterAccessToken {
            get {
                return ((string)(this["TwitterAccessToken"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("d06Gu2YNXtP3ZDieV8SRKYCwCiCkdzTLgKvuExBk4SA")]
        public string TwitterAccessTokenSecret {
            get {
                return ((string)(this["TwitterAccessTokenSecret"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SD Channels")]
        public string ChannelGroup {
            get {
                return ((string)(this["ChannelGroup"]));
            }
        }
    }
}
